#!/usr/bin/env bash
SOURCE_TAG="php:fpm"

if [[ ${DOCKER_TAG} =~ ^5\.([0-3]+).* ]]; then
    SOURCE_TAG="devilbox/php-fpm-${DOCKER_TAG}:latest"
elif [[ ${DOCKER_TAG} != "latest" ]]; then
    SOURCE_TAG="php:${DOCKER_TAG}-fpm"
fi

echo "Start build for source tag ${SOURCE_TAG}"
docker build --build-arg SOURCE_TAG=${SOURCE_TAG} -f ${DOCKERFILE_PATH} -t ${IMAGE_NAME} .